name: client-manager-demo
services:
  postgres:
    image: postgres:17
    restart: always
    container_name: client-manager-postgres
    environment:
      POSTGRES_USER: ${POSTGRES__User}
      POSTGRES_PASSWORD: ${POSTGRES__Password}
      POSTGRES_DB: ${POSTGRES__Database}
      POSTGRES__User: ${POSTGRES__User}
      POSTGRES__Password: ${POSTGRES__Password}
      POSTGRES__Database: ${POSTGRES__Database}
    ports:
      - ${POSTGRES__Port}:${POSTGRES__Port}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES__User}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    container_name: client-manager-rabbitmq
    ports:
      - "${RABBITMQ__AmqpPort}:${RABBITMQ__AmqpPort}" # AMQP
      - "${RABBITMQ__ManagementPort}:${RABBITMQ__ManagementPort}" # Web UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./ClientManager
      dockerfile: ClientManager.API/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:80"
    restart: always
    env_file:
      - ".env"
    environment:
      RABBITMQ__URL: "amqp://rabbitmq"
      POSTGRES__Host: "postgres"
      DOTNET_URLS: "http://+:8080"
      ASPNETCORE_URLS: "http://+:8080"

  worker:
    build:
      context: ./ClientManager
      dockerfile: ClientManager.Worker/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    env_file:
      - ".env"
    environment:
      RABBITMQ__URL: "amqp://rabbitmq"
      POSTGRES__Host: postgres
