services:
  api:
    build:
      context: ./ClientManager
      dockerfile: ClientManager.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    volumes: []

  worker:
    build:
      context: ./ClientManager
      dockerfile: ClientManager.Worker/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    volumes: []

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: false
    volumes: []
