name: client-manager-demo
services:
  postgres:
    image: postgres:17
    restart: always
    container_name: client-manager-postgres
    environment:
      POSTGRES_USER: ${POSTGRES__User}
      POSTGRES_PASSWORD: ${POSTGRES__Password}
      POSTGRES_DB: ${POSTGRES__Database}
      POSTGRES__User: ${POSTGRES__User}
      POSTGRES__Password: ${POSTGRES__Password}
      POSTGRES__Database: ${POSTGRES__Database}
    ports:
      - ${POSTGRES__Port}:${POSTGRES__Port}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES__User}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    container_name: client-manager-rabbitmq
    ports:
      - "${RABBITMQ__AmqpPort}:${RABBITMQ__AmqpPort}" # AMQP
      - "${RABBITMQ__ManagementPort}:${RABBITMQ__ManagementPort}" # Web UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./ClientManager
      dockerfile: ClientManager.API/Dockerfile.dev
    container_name: client-manager-api
    volumes:
      - ./ClientManager/ClientManager.API:/src/ClientManager.API
      - ./ClientManager/ClientManager.Shared:/src/ClientManager.Shared
      - /src/ClientManager.API/bin
      - /src/ClientManager.API/obj
      - /src/ClientManager.Shared/bin
      - /src/ClientManager.Shared/obj
      - ~/.nuget/packages:/root/.nuget/packages
    ports:
      - "5200:5200"
    restart: always
    env_file:
      - ".env"
    environment:
      RABBITMQ__URL: "amqp://rabbitmq"
      POSTGRES__Host: "postgres"
      DOTNET_URLS: "http://+:5200"
      ASPNETCORE_URLS: "http://+:5200"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5200/health || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 5s

  worker:
    build:
      context: ./ClientManager
      dockerfile: ClientManager.Worker/Dockerfile.dev
    container_name: client-manager-worker
    volumes:
      - ./ClientManager/ClientManager.Worker:/src/ClientManager.Worker
      - ./ClientManager/ClientManager.Shared:/src/ClientManager.Shared
      - /src/ClientManager.Worker/bin
      - /src/ClientManager.Worker/obj
      - /src/ClientManager.Shared/bin
      - /src/ClientManager.Shared/obj
      - ~/.nuget/packages:/root/.nuget/packages
    restart: always
    env_file:
      - ".env"
    environment:
      RABBITMQ__URL: "amqp://rabbitmq"
      POSTGRES__Host: postgres
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: client-manager-frontend
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: true
    depends_on:
      api:
        condition: service_healthy
